### ISSUE TITLE
Popup not working

### ISSUE THREAD

**Issue by bamboozila** [DBuit/Homekit-panel-card#106]
Hi, I have some issues with the popup functionnality:

Nothing happens when long pressing my card

Here is my card yml:
```yml
type: 'custom:homekit-card'
home: true
title: Home
useBrightness: false
useTemperature: false
titleColor: '#FFF'
entities:
  - title: Row 1
    popup:
      type: 'custom:light-popup-card'
      scenesInARow: 2
      brightnessWidth: 130px
      brightnessHeight: 350px
      switchWidth: 110px
      switchHeight: 300px
    entities:
      - entity: light.ampoule_bureau_de_francois
        name: Office
        icon: 'mdi:floor-lamp'
```

browser_mod seems to be loaded, js console:

```
BROWSER_MOD 1.3.0 IS INSTALLED    DeviceID: 915d36fd-96b8ed0c
```

EDIT: browser_mod seems to work fine, I tried this code:

```yml
type: button
icon: mdi:star
tap_action:
  action: fire-dom-event
  browser_mod:
    command: toast
    message: Hello, world!
```

 and got:

![image](https://user-images.githubusercontent.com/19970734/110106581-2397df00-7daa-11eb-96c3-368f736346d4.png)
