### ISSUE TITLE
Popup data includes the Entity: Field. 

### ISSUE THREAD

**Issue by EliotHertenstein** [DBuit/Homekit-panel-card#110]
When I try to use a custom popup card, I get an error that the entity: option was removed, even though I never included the entity: option in the popup configuration. 

Here's the error on a mini-graph-card:
<img width="357" alt="Screen Shot 2021-04-09 at 3 42 42 PM" src="https://user-images.githubusercontent.com/39346975/114247652-75ec9280-994a-11eb-80ca-89db6350716a.png">

And here's my yaml:
```
       - entity: sensor.outdoor_temperature
                tap_action:
                  action: popup
                popup:
                  type: 'custom:mini-graph-card'
                  name: Temperature/Humidity
                  icon: 'mdi:thermometer'
                  align_icon: left
                  align_state: center
                  show_fill: false
                  entities:
                    - sensor.outdoor_temperature
```     
For some reason, the entity: field is being included in the popup data.
