### ISSUE TITLE
widerSize does not work

### ISSUE THREAD

**Issue by mew0717** [DBuit/Homekit-panel-card#112]
Sorry for the vague comment/issue reporting.. new to this..but I don't believe the widerSize parameter works.  The tile remains at standard with irrespective of the value...  wider works just fine.

```
- entity: group.ring_backyard_pathlights
  widerSize: 3
  popup:
    type: 'custom:light-popup-card'
    displayType: slider
    actions:
      - service: browser_mod.more_info
        service_data:
          entity_id: group.ring_backyard_pathlights
```
