### ISSUE TITLE
Enable Haptics

### ISSUE THREAD

**Issue by ksmarty** [DBuit/Homekit-panel-card#118]
I'd like to jump on issue #109 as there is no way to enable haptic feedback globally, on a row-by-row basis, or on an individual entity without overwriting `tap_action`. If I'm mistaken please let me know. Thank you!

**Comment by DBuit** [comment]
This is fixed in https://github.com/DBuit/Homekit-panel-card/releases/tag/0.6.2

**Comment by conorlap** [comment]
@DBuit does haptic work on Android (Samsung Galaxy S20+), or just iOS? 

I've added it into my card config, a snippet is below. But no haptic feedback happens! I've ensured to check the "vibrate" radio button under 'Profile' on Home Assistant on that device and have verified that the built in entities cards provides haptic feedback fine.

```
enableColumns: true
home: false
rows:
  - columns:
      - column: 1
        entities:
          - entities:
              - entity: light.living_room
                name: Living Room
                icon: mdi:sofa
              - entity: light.bedroom
                name: Bedroom
                icon: mdi:bed
              - entity: switch.fairy_litez
                name: Fairy Lights
                icon: mdi:string-lights
              - entity: light.office
                name: Office
                icon: phu:rooms-office
              - entity: light.spare_bedroom
                name: Spare Bedroom
                icon: mdi:bed-empty
              - entity: light.hall
                name: Hall
                icon: hue:room-hallway
            title: All Rooms
            **haptic: success**
        tileOnRow: 3
    row: 3
```
