### ISSUE TITLE
You need to define entities: or rows: type: custom:homekit-card

### ISSUE THREAD

**Issue by Neotastisch** [DBuit/Homekit-panel-card#132]
Hey i just put the example code in my view, but i get this error

```
resources:
  url: /hacsfiles/Homekit-panel-card/homekit-panel-card.js
  type: module

title: Home
views:
  - title: Home
    icon: mdi:home-outline
    path: home
    cards:
      - type: custom:homekit-card
```
