### ISSUE TITLE
rulesColor is not working

### ISSUE THREAD

**Issue by briis** [DBuit/Homekit-panel-card#19]
I cannot get *rulesColor* to work. No matter what color I set it to, it stays white - and makes impossible to read on a light background. Below is a snippet of the configuration:

````yaml
      - type: 'custom:homekit-card'
        home: true
        rules: >
          {% if states('sensor.current_lights_on') | float > 0 %} <li>{{states('sensor.current_lights_on')}} {% if states('sensor.current_lights_on') | float > 1 %}lamper {% else %}lampe {% endif %}tændt</li> {% endif %} 
          {% if states('sensor.current_cameras_recording') | float > 0 %} <li>{{states('sensor.current_cameras_recording')}} {% if states('sensor.current_cameras_recording') | float > 1 %}kameraer {% else %}kamera {% endif %}optager</li> {% endif %}
        rulesColor: '#EB5B4C'
````
Am I settings this up wrong?
