### ISSUE TITLE
[idea] Person card

### ISSUE THREAD

**Issue by sauloonze** [DBuit/Homekit-panel-card#25]
I would like to contribute to a more immersive experience when the card is a person. It could be something similar to the weather card. I would like to display the person and devices states.

**Comment by DBuit** [comment]
Hi man,

Sounds cool if you can make a pull request and i will check it out!

**Comment by nawuko** [comment]
I'm currently using a custom sensor to display the time when a state change occured (switching from home to not_home), with ``offStates: ["not_home"]`` you can even "dim" the card so it looks like every other inactive card if the person is not at home.

Currently using a css-rule to display the persons avatar/picture, but looking at the code this could be easily be done with an additional switch rule for person-cards pulling the entity_picture instead of the entity_icon.

![Person Card](https://i.imgur.com/u5sDwte.png)

Maybe some inspiration for proper person card support 👍

**Comment by Freshhat** [comment]
@sauloonze i'm just remodeling my mobile view with the Homekit Panel Card. @DBuit Thanks for it.

For the Person Tile i used the following config:
```  
            - card: picture-entity
                cardOptions:
                  image: /local/pictures/xxx.jpg
                  entity: person.xxx
                  show_name: false
                noPadding: true
                cardStyle: ":host {\n\theight: 100%;\n}\nha-card {\n\tbackground: transparent;\n\tcolor: #E9E9E9;\n\tbox-shadow: none;\n\theight: 100%;\n}\n.header {\n\tpadding: 10px 10px 0 10px;\n}\n.header .name, .header .name .ellipsis {\n\tfont-size: 13px!important;\n\tcolor: #AF8A31;\n\topacity: 1;\n}\n.footer {\n  padding: 0!important;\n  font-size: 12px!important;\n  color: #e9e9e9!important;\n  text-align: center!important;\n}\n"
 ```
Maybe this is what you're searching for
