### ISSUE TITLE
Not displaying anything from lights?

### ISSUE THREAD

**Issue by gbdavidx** [DBuit/Homekit-panel-card#37]
I copied this straight from the example and used my own lights, why doesn't it work? Nothing is displaying icons
```

- title: Lights
  path: lights_path
  cards:
    - type: "custom:homekit-card"
      enableColumns: true
      statePositionTop: true
      rows:
        - row: 1
          columns:
            - column: 1
              tileOnRow: 4
              entities:
                - title: Living Room
                  entities: 
                    - entity: light.tv_light_1  
                    - entity: light.tv_light_2
                    - entity: light.living_room_light
                    - entity: light.living_room_light_r
            - column: 2  
              tileOnRow: 3
              entities:
                - title: Kitchen
                  entities:
                    - entity: light.beganegrond  
        - row: 2
          columns:
            - column: 1
              tileOnRow: 4
              entities:
                - title: Upstairs
                  entities:
                    - entity: binary_sensor.wasmachine_status
                    - entity: weather.weersverwachting
        - row: 3
          columns:
            - column: 1
              entities:
                - title: Bedroom
                  entities:
                    - entity: switch.doorbell_chime_active
```

**Comment by DBuit** [comment]
Hi,

hard to say why you can add `icon:` for each `entity:` and set your own icon like this:

```
- row: 3
          columns:
            - column: 1
              entities:
                - title: Bedroom
                  entities:
                    - entity: switch.doorbell_chime_active
                       icon: mdi:lightbulb
```
