### ISSUE TITLE
Last changed state on more devices than sensors

### ISSUE THREAD

**Issue by acateon** [DBuit/Homekit-panel-card#40]
If I'm not misstaken there's as of now not possible to show last_changed state on other devices than sensors. A nice addon would be to be able to show last_changed state for every device that supports it.

Example below:

```
entities:
  - entity: person.xxxxxxx
    popup:
      type: map
      default_zoom: 16
      dark_mode: true
      entities:
        - person.xxxxx
    state: last_changed
    icon: mdi:human-female
    name: Linn
    offStates:
      - "Borta"
      - "not_home"
      - "paused"
```
