### ISSUE TITLE
[request] Weather card

### ISSUE THREAD

**Issue by yvesfouquet4** [DBuit/Homekit-panel-card#49]
Hi, i dont know if its meant to work but i wanted to add the "weather card" or "simple weather card" to the homekit panel config but it doesnt seem to work. 

thanks in advance

code
```
              - column: 2
                entities:
                  - entities:
                      - entity: weather.breucq
                      - card: 'custom:weather-card'
                        cardOptions:
                          entities:
                            - entity: 'weather.breucq'
                        noPadding: true
                      - card: 'custom:simple-weather-card'
                        cardOptions:
                          entities:
                            - entity: 'weather.breucq'
                        noPadding: true
                      - card: 'custom:mini-graph-card'
                        cardOptions:
                          entities:
                            - sensor.temp_zithoek
                          update_interval: 1
                        noPadding: true
                      - card: 'custom:mini-graph-card'
                        cardOptions:
                          entities:
                            - sensor.temp_leefruimte
                          update_interval: 1
                        noPadding: true
                    title: Temperatuur
                tileOnRow: 3
```

result
![afbeelding](https://user-images.githubusercontent.com/8839059/81829737-81b5b600-953b-11ea-8a26-1496ebe35878.png)

**Comment by Freshhat** [comment]
Try this one:

```              
              - card: weather-forecast
                cardOptions:
                  entity: weather.dark_sky
                  name: ' '
                  show_forecast: false
                cardStyle: ":host {\n\theight: 100%;\n}\nha-card { background: transparent;\n\tcolor: #E9E9E9;\n\tbox-shadow: none;\n}\n.header {\n\tpadding: 10px 10px 0 10px;\n}\n.header .name, .header .name .ellipsis {\n\tfont-size: 13px!important;\n\tfont-weight: 500;\n\tcolor: #AF8A31;\n\topacity: 1;\n}\n.header icon {\n\tcolor: #f7d959;\n}\n.states {\n\tpadding: 0 10px;\n}\n.states .state {\n\tfont-size: 10px;\n}\n.header .icon {\n\tcolor: #f7d959;\n}\n"
                noPadding: true
```
