### ISSUE TITLE
[ request ] show picture in card

### ISSUE THREAD

**Issue by yvesfouquet4** [DBuit/Homekit-panel-card#50]
I added pictures to the person entity but it doesnt show in the card
```
    cards:
      - enableColumns: true
        rows:
          - columns:
              - column: 1
                entities:
                  - entities:
                      - entity: person.toulouse
                      - entity: person.babette
                tileOnRow: 3
            row: 1
        type: 'custom:homekit-card'
```

result:
![afbeelding](https://user-images.githubusercontent.com/8839059/81886014-ef91ca00-959b-11ea-9fb7-87f46a574104.png)
should be:
![afbeelding](https://user-images.githubusercontent.com/8839059/81886037-ffa9a980-959b-11ea-8035-e984bd10bcd3.png)
