### ISSUE TITLE
Number Format  - number.toLocaleString ?

### ISSUE THREAD

**Issue by zibous** [DBuit/Homekit-panel-card#67]
Is there any way to format the representation of the number for a card ?

![Bildschirmfoto 2020-07-20 um 15 07 34](https://user-images.githubusercontent.com/30198737/87942628-2b19aa80-ca9d-11ea-90d5-1024167a18ef.png)

```yaml
entities:
  - title: "Wasserverbrauch"
    entities:
      - entity: sensor.wasser_liter_jahr
        name: Jahr
        localestring: 'de-AT'                     ##  this way ??
        tap_action:
          action: more-info
          entity: sensor.wasser_liter_jahr
```

Result for  number.toLocaleString(localestring):
```javascript
Number(54123.990).toLocaleString("de-DE")
"54.123,99"
```
