### ISSUE TITLE
Homekit-panel-card popup thermostat-popup-card

### ISSUE THREAD

**Issue by MantasIgnatjevas** [DBuit/Homekit-panel-card#70]
Hey there.

I am trying to configure my dashboard with Homekit panel card. I am trying to do this for my air conditioner (connected through SmartThings). But there is no popup. No errors too.

This is what I have in my overview (the card shows up fine, I see the current temperature from AC sensor, and the temperature of the last AC on that was set)
```           
   - entity: climate.room_air_conditioner
                popup:
                  type: 'custom:thermostat-popup-card'
```
This is what I have in ui-lovelace.yaml
```
popup_cards:
  climate.room_air_conditioner:
    title: "Dining room AC"
    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.8)
      flex-direction: column
      margin: 0
      "--iron-icon-fill-color": "#FFF"
    card:
      type: custom:thermostat-popup-card
      entity: climate.room_air_conditioner
```
The popup does not popup neither on pc, on tablet nor phone. When I hold it on the phone/table it has haptic feedback (small vibration) but nothing pops up.
What am I doing wrong here? Thank you.

**Comment by DBuit** [comment]
The second part `popup_cards` is something from browser mod.
This overwrites the default more-info popup with a custom card.

If you have this setup you do not need to add `popup` in the home-kit card because browser-mod already fixes the popup for you.

But if you want the popup to open when holding or tap the tile you need to set an action.

Example for the hold action:

```
   - entity: climate.room_air_conditioner
     hold_action:
       action: more-info
       entity: climate.room_air_conditioner

```
