### ISSUE TITLE
Sensor entities always display last_changed despite the state option.

### ISSUE THREAD

**Issue by mmonkey** [DBuit/Homekit-panel-card#71]
Any time the entity is a sensor, last_change always displays.

```
- type: 'custom:homekit-card'
  enableColumns: true
  rows:
    - row: 1
      columns:
        - column: 1
          tileOnRow: 2
          entities:
            - title: Entertainment
              entities:
                - entity: sensor.sound_bar_sound
                  icon: mdi:volume-mute
                  offIcon: mdi:volume-low
                  state: false
                  offStates:
                    - "unmuted"
                  tap_action:
                    action: toggle
                    entity: switch.sound_bar_sound
```
