### ISSUE TITLE
Option to concatenate attributes / strings in statePath

### ISSUE THREAD

**Issue by jeqermigselv-cloud** [DBuit/Homekit-panel-card#90]
Having the possibility to combine strings and attributes in the statePath option would be of great help.

Meaning that it would possible to do like so:
```
            entities:
              - entity: entityName
                state: sensor.entityWatchState
                statePath: attributes.track + string + attribute

```
