### ISSUE TITLE
Blank card with lots of JS errors

### ISSUE THREAD

**Issue by cyberjacob** [DBuit/Homekit-panel-card#98]
Not entirely sure what's causing this. I'm trying to set up the Homekit panel card for the first time and keep encountering this issue. Seems to be various config changes that cause it, however reverting the changes does not fix the card. I'm not entirely sure what I'm doing that does manage to fix it.

JS Traceback:
```js
Uncaught (in promise) TypeError: row.entities is undefined
    _renderEntities homekit-panel-card.js:6777
    _renderEntities homekit-panel-card.js:6772
    _renderRows homekit-panel-card.js:6628
    _renderRows homekit-panel-card.js:6625
    _renderRows homekit-panel-card.js:6622
    render homekit-panel-card.js:6560
    update app.924deda6.js:10297
    performUpdate app.924deda6.js:10297
    _enqueueUpdate app.924deda6.js:10297
    requestUpdateInternal app.924deda6.js:10297
    set app.924deda6.js:10297
    value chunk.72df0e2934b88fac4ebc.js:1
    performUpdate app.924deda6.js:10297
    _enqueueUpdate app.924deda6.js:10297
    requestUpdateInternal app.924deda6.js:10297
    set app.924deda6.js:10297
    commit app.924deda6.js:10297
    commit app.924deda6.js:10297
    update app.924deda6.js:10297
    __commitTemplateResult app.924deda6.js:10297
    commit app.924deda6.js:10297
    a app.924deda6.js:10297
    render app.924deda6.js:10297
    update app.924deda6.js:10297
    performUpdate app.924deda6.js:10297
    _enqueueUpdate app.924deda6.js:10297
    requestUpdateInternal app.924deda6.js:10297
    set app.924deda6.js:10297
    value app.924deda6.js:41607
    value app.924deda6.js:41607
    value app.924deda6.js:44533
    performUpdate app.924deda6.js:10297
    _enqueueUpdate app.924deda6.js:10297
    requestUpdateInternal app.924deda6.js:10297
    set app.924deda6.js:10297
    value app.924deda6.js:41607
    hassConnected app.924deda6.js:41607
    s core.94ddb68d.js:1
    f core.94ddb68d.js:1
    f core.94ddb68d.js:1
    _handleMessage core.94ddb68d.js:1
    setSocket core.94ddb68d.js:1
```

Minimum card config that still causes the issue
```yaml
type: 'custom:homekit-card'
entities:
  - card: weather-forecast
    wider: true
    cardOptions:
      entity: weather.met_office_xxx_daily
```

**Comment by DBuit** [comment]
Hello @cyberjacob 

Your are missing the row part:
```
type: 'custom:homekit-card'
  entities:
  - title: Weather cards
    entities:
      - card: weather-forecast
      wider: true
      cardOptions:
        entity: weather.met_office_xxx_daily
```
